---
apiVersion: v1
kind: Service
metadata:
  name: springboot-hello-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: springboot-hello
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080